name: my first action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps:
        - name: Checkout repository
        uses: actions/checkout@v4

        - name: My first action
        run: echo "Hello, World!"

        - name: List all files
        run: ls