name: action 2

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 2
        uses: actions/checkout@v4

      - name: Executing shell script
        run: |
          chmod +x asci-script.sh
          ./asci-script.sh